schema: "./services/**/schema.graphql"
generates:
  ./generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
  ./generated/graphql.schema.json:
    plugins:
      - "introspection"
  